BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[todos] (
    [id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF__todos__id__3D5E1FD2] DEFAULT newid(),
    [text] NVARCHAR(max) NOT NULL,
    [completed] BIT CONSTRAINT [DF__todos__completed__3E52440B] DEFAULT 0,
    [created_at] DATETIMEOFFSET CONSTRAINT [DF__todos__created_a__3F466844] DEFAULT CURRENT_TIMESTAMP,
    [updated_at] DATETIMEOFFSET CONSTRAINT [DF__todos__updated_a__403A8C7D] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [PK__todos__3213E83F26E033D0] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
